"""
Skills_Assessment_Agent — Agent State
Auto-generated by MAFIA. Customize as needed.
"""
from typing import Annotated, Any, Dict, List, Optional
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from enum import Enum


class AgentPhase(str, Enum):
    """Workflow phases — auto-generated from system prompt analysis."""
    INITIATED = "initiated"
    PROFILE_FETCH = "profile_fetch"
    SKILL_MATRIX_RETRIEVAL = "skill_matrix_retrieval"
    CURRENT_SKILLS_EVAL = "current_skills_eval"
    SELF_ASSESSMENT = "self_assessment"
    MANAGER_ASSESSMENT = "manager_assessment"
    GAP_ANALYSIS = "gap_analysis"
    REPORT_GENERATION = "report_generation"
    COMPLETED = "completed"
    NEEDS_CORRECTION = "needs_correction"
    COMPLETED        = "completed"
    REJECTED         = "rejected"
    NEEDS_CORRECTION = "needs_correction"


class Skills_Assessment_AgentState(TypedDict):
    """
    Complete state for Skills_Assessment_Agent.
    Auto-generated by MAFIA from system prompt analysis.
    """

    # ── CAMS Required Fields (DO NOT REMOVE) ──────────────────
    messages: Annotated[List[BaseMessage], add_messages]
    tenant_id: str
    thread_id: str
    _langfuse_trace_id: Optional[str]
    _langfuse_span_id: Optional[str]
    litellm_headers: Optional[dict]
    needs_retrieval: bool
    search_query: str
    retrieved_context: str

    # ── Workflow Tracking ──────────────────────────────────────
    current_phase: str
    phase_history: List[Dict[str, Any]]
    errors: List[str]
    final_response: str

    # ── Agent-Specific Fields (from prompt analysis) ───────────
    # Unique ID for the employee's assessment
    assessment_id: str
    # Unique ID for the employee
    emp_id: str
    # Employee's full name
    full_name: str
    # Employee's designation
    designation: str
    # Employee's department
    department: str
    # ID of the employee's manager
    manager_id: str
    # Employee's UAN for PF status check
    uan: str
    # Employee's ESIC number for ESIC status check
    esic_no: str
    # Employee's PF status
    pf_status: str
    # Employee's ESIC status
    esic_status: str
    # Required skills for the employee's role
    skill_matrix: dict
    # Employee's current skills
    current_skills: list
    # Employee's certifications
    certifications: list
    # Employee's training history
    training_history: list
    # Score from the employee's self-assessment
    self_assessment_score: float
    # Score from the manager's assessment
    manager_assessment_score: float
    # Identified skill gaps
    skill_gaps: dict
    # Learning and development recommendations
    recommendations: list
    # Flags for compliance-related issues
    compliance_flags: dict
    # URL to access the generated report
    report_url: str
    # Reason for requiring correction
    correction_reason: Optional[str]
