"""
MOFSL_Account_Onboarding_Assistant — Agent State
Auto-generated by MAFIA. Customize as needed.
"""
from typing import Annotated, Any, Dict, List, Optional
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from enum import Enum


class AgentPhase(str, Enum):
    """Workflow phases — auto-generated from system prompt analysis."""
    INITIATE_EKYC = "initiate_ekyc"
    COLLECT_CLIENT_INFORMATION = "collect_client_information"
    FACILITATE_ONBOARDING = "facilitate_onboarding"
    COORDINATE_WITH_DEPARTMENTS = "coordinate_with_departments"
    VERIFY_AND_SUBMIT_APPLICATIONS = "verify_and_submit_applications"
    COMPLETED        = "completed"
    REJECTED         = "rejected"
    NEEDS_CORRECTION = "needs_correction"


class MOFSL_Account_Onboarding_AssistantState(TypedDict):
    """
    Complete state for MOFSL_Account_Onboarding_Assistant.
    Auto-generated by MAFIA from system prompt analysis.
    """

    # ── CAMS Required Fields (DO NOT REMOVE) ──────────────────
    messages: Annotated[List[BaseMessage], add_messages]
    tenant_id: str
    thread_id: str
    _langfuse_trace_id: Optional[str]
    _langfuse_span_id: Optional[str]
    litellm_headers: Optional[dict]
    needs_retrieval: bool
    search_query: str
    retrieved_context: str

    # ── Workflow Tracking ──────────────────────────────────────
    current_phase: str
    phase_history: List[Dict[str, Any]]
    errors: List[str]
    final_response: str

    # ── Agent-Specific Fields (from prompt analysis) ───────────
    # Tracks the client ID during the onboarding process.
    client_id: Optional[str]
    # Tracks the status of the client's application.
    application_status: Optional[str]
    # Tracks if coordination with departments is complete.
    coordination_status: Optional[bool]
