"""
EXECUTOR PATCH for Skills_Assessment_Agent
=========================================
INSTRUCTIONS:
1. Open src/agent/executor.py
2. Find the build_graph() method
3. Replace its entire body with the code below
=========================================
Auto-generated by MAFIA.
"""

# ── Paste this inside build_graph() in executor.py ───────────

def build_graph(self, tenant_id: str = "default"):
    """
    Skills_Assessment_Agent — 10-phase workflow
    Auto-generated by MAFIA from system prompt analysis.
    """
    from langgraph.graph import StateGraph, END
    from .nodes.agent_state import Skills_Assessment_AgentState
    from .nodes.agent_nodes import InitiatedNode
    from .nodes.agent_nodes import ProfileFetchNode
    from .nodes.agent_nodes import SkillMatrixRetrievalNode
    from .nodes.agent_nodes import CurrentSkillsEvalNode
    from .nodes.agent_nodes import SelfAssessmentNode
    from .nodes.agent_nodes import ManagerAssessmentNode
    from .nodes.agent_nodes import GapAnalysisNode
    from .nodes.agent_nodes import ReportGenerationNode
    from .nodes.agent_nodes import CompletedNode
    from .nodes.agent_nodes import NeedsCorrectionNode

    workflow = StateGraph(Skills_Assessment_AgentState)

    # ── Initialize nodes ──────────────────────────────────
    initiated_node = InitiatedNode(self.config, tenant_id)
    profile_fetch_node = ProfileFetchNode(self.config, tenant_id)
    skill_matrix_retrieval_node = SkillMatrixRetrievalNode(self.config, tenant_id)
    current_skills_eval_node = CurrentSkillsEvalNode(self.config, tenant_id)
    self_assessment_node = SelfAssessmentNode(self.config, tenant_id)
    manager_assessment_node = ManagerAssessmentNode(self.config, tenant_id)
    gap_analysis_node = GapAnalysisNode(self.config, tenant_id)
    report_generation_node = ReportGenerationNode(self.config, tenant_id)
    completed_node = CompletedNode(self.config, tenant_id)
    needs_correction_node = NeedsCorrectionNode(self.config, tenant_id)

    # ── Register nodes ────────────────────────────────────
    workflow.add_node("initiated", initiated_node.execute)
    workflow.add_node("profile_fetch", profile_fetch_node.execute)
    workflow.add_node("skill_matrix_retrieval", skill_matrix_retrieval_node.execute)
    workflow.add_node("current_skills_eval", current_skills_eval_node.execute)
    workflow.add_node("self_assessment", self_assessment_node.execute)
    workflow.add_node("manager_assessment", manager_assessment_node.execute)
    workflow.add_node("gap_analysis", gap_analysis_node.execute)
    workflow.add_node("report_generation", report_generation_node.execute)
    workflow.add_node("completed", completed_node.execute)
    workflow.add_node("needs_correction", needs_correction_node.execute)
    workflow.add_node("completed",        lambda s: s)
    workflow.add_node("rejected",         lambda s: s)
    workflow.add_node("needs_correction", lambda s: s)

    # ── Wire edges ────────────────────────────────────────
    workflow.set_entry_point("initiated")
    workflow.add_edge("initiated", "profile_fetch")
    workflow.add_edge("profile_fetch", "skill_matrix_retrieval")
    workflow.add_edge("skill_matrix_retrieval", "current_skills_eval")
    workflow.add_edge("current_skills_eval", "self_assessment")
    workflow.add_edge("self_assessment", "manager_assessment")
    workflow.add_edge("manager_assessment", "gap_analysis")
    workflow.add_edge("gap_analysis", "report_generation")
    workflow.add_edge("report_generation", "completed")
    workflow.add_edge("completed", "needs_correction")
    workflow.add_edge("needs_correction", "completed")
    workflow.add_edge("completed",        END)
    workflow.add_edge("rejected",         END)
    workflow.add_edge("needs_correction", END)

    return workflow
