"""
EXECUTOR PATCH for MOFSL_Account_Onboarding_Assistant
=========================================
INSTRUCTIONS:
1. Open src/agent/executor.py
2. Find the build_graph() method
3. Replace its entire body with the code below
=========================================
Auto-generated by MAFIA.
"""

# ── Paste this inside build_graph() in executor.py ───────────

def build_graph(self, tenant_id: str = "default"):
    """
    MOFSL_Account_Onboarding_Assistant — 5-phase workflow
    Auto-generated by MAFIA from system prompt analysis.
    """
    from langgraph.graph import StateGraph, END
    from .nodes.agent_state import MOFSL_Account_Onboarding_AssistantState
    from .nodes.agent_nodes import InitiateEkycNode
    from .nodes.agent_nodes import CollectClientInformationNode
    from .nodes.agent_nodes import FacilitateOnboardingNode
    from .nodes.agent_nodes import CoordinateWithDepartmentsNode
    from .nodes.agent_nodes import VerifyAndSubmitApplicationsNode

    workflow = StateGraph(MOFSL_Account_Onboarding_AssistantState)

    # ── Initialize nodes ──────────────────────────────────
    initiate_ekyc_node = InitiateEkycNode(self.config, tenant_id)
    collect_client_information_node = CollectClientInformationNode(self.config, tenant_id)
    facilitate_onboarding_node = FacilitateOnboardingNode(self.config, tenant_id)
    coordinate_with_departments_node = CoordinateWithDepartmentsNode(self.config, tenant_id)
    verify_and_submit_applications_node = VerifyAndSubmitApplicationsNode(self.config, tenant_id)

    # ── Register nodes ────────────────────────────────────
    workflow.add_node("initiate_ekyc", initiate_ekyc_node.execute)
    workflow.add_node("collect_client_information", collect_client_information_node.execute)
    workflow.add_node("facilitate_onboarding", facilitate_onboarding_node.execute)
    workflow.add_node("coordinate_with_departments", coordinate_with_departments_node.execute)
    workflow.add_node("verify_and_submit_applications", verify_and_submit_applications_node.execute)
    workflow.add_node("completed",        lambda s: s)
    workflow.add_node("rejected",         lambda s: s)
    workflow.add_node("needs_correction", lambda s: s)

    # ── Wire edges ────────────────────────────────────────
    workflow.set_entry_point("initiate_ekyc")
    workflow.add_edge("initiate_ekyc", "collect_client_information")
    workflow.add_edge("collect_client_information", "facilitate_onboarding")
    workflow.add_edge("facilitate_onboarding", "coordinate_with_departments")
    workflow.add_edge("coordinate_with_departments", "verify_and_submit_applications")
    workflow.add_edge("verify_and_submit_applications", "completed")
    workflow.add_edge("completed",        END)
    workflow.add_edge("rejected",         END)
    workflow.add_edge("needs_correction", END)

    return workflow
