"""
Tool: activate_account
Description: Generate UCC and DP ID in CBOS
API: MOFSL CBOS Back-Office API
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def activate_account(application_id: str, pan_number: str, account_type: str) -> str:
    """Generate UCC and DP ID in CBOS"""
    if MOCK_MODE:
        return '{"activated": true, "ucc_code": "MO12ABCD34", "dp_id": "IN300000123456"}'

    # TODO: Replace with real MOFSL CBOS Back-Office API call
    url = os.getenv("ACTIVATE_ACCOUNT_URL", "")
    api_key = os.getenv("ACTIVATE_ACCOUNT_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "ACTIVATE_ACCOUNT_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"application_id": application_id, "pan_number": pan_number, "account_type": account_type},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "activate_account"})
