"""
Tool: collect_client_data
Description: Collect essential client information for account activation.
API: 
Auto-generated by MAFIA — implement real_collect_client_data() with your API call.
"""
import os
import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


async def mock_collect_client_data(client_form: str) -> dict:
    """
    Mock implementation for testing.
    Returns realistic test data — no real API called.
    """
    return {
        "success": True
}


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=4))
async def real_collect_client_data(client_form: str) -> dict:
    """
    TODO: Implement real  call here.

    Steps:
    1. Get API URL from environment: os.getenv("COLLECT_CLIENT_DATA_URL")
    2. Get API key: os.getenv("COLLECT_CLIENT_DATA_API_KEY")
    3. Make the HTTP call
    4. Return structured response
    """
    url = os.getenv("COLLECT_CLIENT_DATA_URL", "")
    api_key = os.getenv("COLLECT_CLIENT_DATA_API_KEY", "")

    if not url:
        raise ValueError("COLLECT_CLIENT_DATA_URL not set in environment")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            json={"client_form": client_form},
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        response.raise_for_status()
        return response.json()


async def collect_client_data(client_form: str) -> dict:
    """
    Collect essential client information for account activation.
    Automatically switches between mock and real based on MOCK_MODE env var.
    Set MOCK_MODE=false for production.
    """
    try:
        if MOCK_MODE:
            return await mock_collect_client_data(client_form)
        return await real_collect_client_data(client_form)
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "tool": "collect_client_data",
            "mock_mode": MOCK_MODE
        }


# ── Claude Tool Schema ─────────────────────────────────────────
# Auto-registered by CAMS tool registry when placed in src/tools/

TOOL_SCHEMA = {
    "name": "collect_client_data",
    "description": "Collect essential client information for account activation.",
    "input_schema": {
        "type": "object",
        "properties": {
            "client_form": {"type": "string", "description": "Form containing all client information."}
        },
        "required": ["client_form"]
    }
}
