"""
Tool: coordinate_departments
Description: Coordinate with MOFSL departments for process adherence.
API: 
Auto-generated by MAFIA — implement real_coordinate_departments() with your API call.
"""
import os
import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


async def mock_coordinate_departments(department_list: str) -> dict:
    """
    Mock implementation for testing.
    Returns realistic test data — no real API called.
    """
    return {
        "success": True
}


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=4))
async def real_coordinate_departments(department_list: str) -> dict:
    """
    TODO: Implement real  call here.

    Steps:
    1. Get API URL from environment: os.getenv("COORDINATE_DEPARTMENTS_URL")
    2. Get API key: os.getenv("COORDINATE_DEPARTMENTS_API_KEY")
    3. Make the HTTP call
    4. Return structured response
    """
    url = os.getenv("COORDINATE_DEPARTMENTS_URL", "")
    api_key = os.getenv("COORDINATE_DEPARTMENTS_API_KEY", "")

    if not url:
        raise ValueError("COORDINATE_DEPARTMENTS_URL not set in environment")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            json={"department_list": department_list},
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        response.raise_for_status()
        return response.json()


async def coordinate_departments(department_list: str) -> dict:
    """
    Coordinate with MOFSL departments for process adherence.
    Automatically switches between mock and real based on MOCK_MODE env var.
    Set MOCK_MODE=false for production.
    """
    try:
        if MOCK_MODE:
            return await mock_coordinate_departments(department_list)
        return await real_coordinate_departments(department_list)
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "tool": "coordinate_departments",
            "mock_mode": MOCK_MODE
        }


# ── Claude Tool Schema ─────────────────────────────────────────
# Auto-registered by CAMS tool registry when placed in src/tools/

TOOL_SCHEMA = {
    "name": "coordinate_departments",
    "description": "Coordinate with MOFSL departments for process adherence.",
    "input_schema": {
        "type": "object",
        "properties": {
            "department_list": {"type": "string", "description": "List of departments to coordinate with."}
        },
        "required": ["department_list"]
    }
}
