"""
Tool: fetch_training_history
Description: Retrieves training history of an employee
API: LMS API
Auto-generated by MAFIA — implement real_fetch_training_history() with your API call.
"""
import os
import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


async def mock_fetch_training_history(emp_id: str) -> dict:
    """
    Mock implementation for testing.
    Returns realistic test data — no real API called.
    """
    return {
        "success": True
}


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=4))
async def real_fetch_training_history(emp_id: str) -> dict:
    """
    TODO: Implement real LMS API call here.

    Steps:
    1. Get API URL from environment: os.getenv("FETCH_TRAINING_HISTORY_URL")
    2. Get API key: os.getenv("FETCH_TRAINING_HISTORY_API_KEY")
    3. Make the HTTP call
    4. Return structured response
    """
    url = os.getenv("FETCH_TRAINING_HISTORY_URL", "")
    api_key = os.getenv("FETCH_TRAINING_HISTORY_API_KEY", "")

    if not url:
        raise ValueError("FETCH_TRAINING_HISTORY_URL not set in environment")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            json={"emp_id": emp_id},
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        response.raise_for_status()
        return response.json()


async def fetch_training_history(emp_id: str) -> dict:
    """
    Retrieves training history of an employee
    Automatically switches between mock and real based on MOCK_MODE env var.
    Set MOCK_MODE=false for production.
    """
    try:
        if MOCK_MODE:
            return await mock_fetch_training_history(emp_id)
        return await real_fetch_training_history(emp_id)
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "tool": "fetch_training_history",
            "mock_mode": MOCK_MODE
        }


# ── Claude Tool Schema ─────────────────────────────────────────
# Auto-registered by CAMS tool registry when placed in src/tools/

TOOL_SCHEMA = {
    "name": "fetch_training_history",
    "description": "Retrieves training history of an employee",
    "input_schema": {
        "type": "object",
        "properties": {
            "emp_id": {"type": "string", "description": "Employee ID to fetch training history"}
        },
        "required": ["emp_id"]
    }
}
