"""
Tool: fetch_skill_matrix
Description: Retrieves role-based skill matrix
API: Darwinbox Skill Matrix API
Auto-generated by MAFIA — implement real_fetch_skill_matrix() with your API call.
"""
import os
import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


async def mock_fetch_skill_matrix(role: str, department: str) -> dict:
    """
    Mock implementation for testing.
    Returns realistic test data — no real API called.
    """
    return {
        "success": True
}


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=4))
async def real_fetch_skill_matrix(role: str, department: str) -> dict:
    """
    TODO: Implement real Darwinbox Skill Matrix API call here.

    Steps:
    1. Get API URL from environment: os.getenv("FETCH_SKILL_MATRIX_URL")
    2. Get API key: os.getenv("FETCH_SKILL_MATRIX_API_KEY")
    3. Make the HTTP call
    4. Return structured response
    """
    url = os.getenv("FETCH_SKILL_MATRIX_URL", "")
    api_key = os.getenv("FETCH_SKILL_MATRIX_API_KEY", "")

    if not url:
        raise ValueError("FETCH_SKILL_MATRIX_URL not set in environment")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            json={"role": role, "department": department},
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        response.raise_for_status()
        return response.json()


async def fetch_skill_matrix(role: str, department: str) -> dict:
    """
    Retrieves role-based skill matrix
    Automatically switches between mock and real based on MOCK_MODE env var.
    Set MOCK_MODE=false for production.
    """
    try:
        if MOCK_MODE:
            return await mock_fetch_skill_matrix(role, department)
        return await real_fetch_skill_matrix(role, department)
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "tool": "fetch_skill_matrix",
            "mock_mode": MOCK_MODE
        }


# ── Claude Tool Schema ─────────────────────────────────────────
# Auto-registered by CAMS tool registry when placed in src/tools/

TOOL_SCHEMA = {
    "name": "fetch_skill_matrix",
    "description": "Retrieves role-based skill matrix",
    "input_schema": {
        "type": "object",
        "properties": {
            "role": {"type": "string", "description": "Role for which skills are needed"},
            "department": {"type": "string", "description": "Department associated with the role"}
        },
        "required": ["role", "department"]
    }
}
