"""
Tool: generate_report
Description: Compiles the assessment report including compliance checks
API: Internal Report Service
Auto-generated by MAFIA — implement real_generate_report() with your API call.
"""
import os
import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


async def mock_generate_report(emp_id: str, assessment_id: str, gap_summary: dict) -> dict:
    """
    Mock implementation for testing.
    Returns realistic test data — no real API called.
    """
    return {
        "success": True
}


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=4))
async def real_generate_report(emp_id: str, assessment_id: str, gap_summary: dict) -> dict:
    """
    TODO: Implement real Internal Report Service call here.

    Steps:
    1. Get API URL from environment: os.getenv("GENERATE_REPORT_URL")
    2. Get API key: os.getenv("GENERATE_REPORT_API_KEY")
    3. Make the HTTP call
    4. Return structured response
    """
    url = os.getenv("GENERATE_REPORT_URL", "")
    api_key = os.getenv("GENERATE_REPORT_API_KEY", "")

    if not url:
        raise ValueError("GENERATE_REPORT_URL not set in environment")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            json={"emp_id": emp_id, "assessment_id": assessment_id, "gap_summary": gap_summary},
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        response.raise_for_status()
        return response.json()


async def generate_report(emp_id: str, assessment_id: str, gap_summary: dict) -> dict:
    """
    Compiles the assessment report including compliance checks
    Automatically switches between mock and real based on MOCK_MODE env var.
    Set MOCK_MODE=false for production.
    """
    try:
        if MOCK_MODE:
            return await mock_generate_report(emp_id, assessment_id, gap_summary)
        return await real_generate_report(emp_id, assessment_id, gap_summary)
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "tool": "generate_report",
            "mock_mode": MOCK_MODE
        }


# ── Claude Tool Schema ─────────────────────────────────────────
# Auto-registered by CAMS tool registry when placed in src/tools/

TOOL_SCHEMA = {
    "name": "generate_report",
    "description": "Compiles the assessment report including compliance checks",
    "input_schema": {
        "type": "object",
        "properties": {
            "emp_id": {"type": "string", "description": "Employee ID for report generation"},
            "assessment_id": {"type": "string", "description": "Assessment ID for the report"},
            "gap_summary": {"type": "dict", "description": "Summary of skill gap analysis"}
        },
        "required": ["emp_id", "assessment_id", "gap_summary"]
    }
}
