"""
Tool: process_ckyc
Description: Search and upload CKYC to CERSAI
API: CERSAI HTTP API
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def process_ckyc(pan_number: str, full_name: str) -> str:
    """Search and upload CKYC to CERSAI"""
    if MOCK_MODE:
        return '{"ckyc_number": "CKYC-MOCK-001", "already_existed": false}'

    # TODO: Replace with real CERSAI HTTP API call
    url = os.getenv("PROCESS_CKYC_URL", "")
    api_key = os.getenv("PROCESS_CKYC_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "PROCESS_CKYC_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"pan_number": pan_number, "full_name": full_name},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "process_ckyc"})
