"""
Tool: run_gap_analysis
Description: Performs skill gap analysis based on required and current skills
API: Internal Skill Gap Engine
Auto-generated by MAFIA — implement real_run_gap_analysis() with your API call.
"""
import os
import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


async def mock_run_gap_analysis(emp_id: str, required_skills: list, current_skills: list) -> dict:
    """
    Mock implementation for testing.
    Returns realistic test data — no real API called.
    """
    return {
        "success": True
}


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=4))
async def real_run_gap_analysis(emp_id: str, required_skills: list, current_skills: list) -> dict:
    """
    TODO: Implement real Internal Skill Gap Engine call here.

    Steps:
    1. Get API URL from environment: os.getenv("RUN_GAP_ANALYSIS_URL")
    2. Get API key: os.getenv("RUN_GAP_ANALYSIS_API_KEY")
    3. Make the HTTP call
    4. Return structured response
    """
    url = os.getenv("RUN_GAP_ANALYSIS_URL", "")
    api_key = os.getenv("RUN_GAP_ANALYSIS_API_KEY", "")

    if not url:
        raise ValueError("RUN_GAP_ANALYSIS_URL not set in environment")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            json={"emp_id": emp_id, "required_skills": required_skills, "current_skills": current_skills},
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        response.raise_for_status()
        return response.json()


async def run_gap_analysis(emp_id: str, required_skills: list, current_skills: list) -> dict:
    """
    Performs skill gap analysis based on required and current skills
    Automatically switches between mock and real based on MOCK_MODE env var.
    Set MOCK_MODE=false for production.
    """
    try:
        if MOCK_MODE:
            return await mock_run_gap_analysis(emp_id, required_skills, current_skills)
        return await real_run_gap_analysis(emp_id, required_skills, current_skills)
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "tool": "run_gap_analysis",
            "mock_mode": MOCK_MODE
        }


# ── Claude Tool Schema ─────────────────────────────────────────
# Auto-registered by CAMS tool registry when placed in src/tools/

TOOL_SCHEMA = {
    "name": "run_gap_analysis",
    "description": "Performs skill gap analysis based on required and current skills",
    "input_schema": {
        "type": "object",
        "properties": {
            "emp_id": {"type": "string", "description": "Employee ID for gap analysis"},
            "required_skills": {"type": "list", "description": "List of required skills"},
            "current_skills": {"type": "list", "description": "List of current skills"}
        },
        "required": ["emp_id", "required_skills", "current_skills"]
    }
}
