"""
Tool: screen_aml
Description: Screen customer for AML/PEP compliance
API: AML Vendor API
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def screen_aml(full_name: str, pan_number: str) -> str:
    """Screen customer for AML/PEP compliance"""
    if MOCK_MODE:
        return '{"risk_level": "low", "is_pep": false, "screening_ref": "AML-MOCK-001"}'

    # TODO: Replace with real AML Vendor API call
    url = os.getenv("SCREEN_AML_URL", "")
    api_key = os.getenv("SCREEN_AML_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "SCREEN_AML_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"full_name": full_name, "pan_number": pan_number},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "screen_aml"})
