"""
Tool: send_notification
Description: Send notification via SMS/Email/WhatsApp
API: MSG91 / SMTP / WhatsApp Business API
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def send_notification(mobile: str, message: str, channel: str) -> str:
    """Send notification via SMS/Email/WhatsApp"""
    if MOCK_MODE:
        return '{"sent": true, "message_id": "MSG-MOCK-001"}'

    # TODO: Replace with real MSG91 / SMTP / WhatsApp Business API call
    url = os.getenv("SEND_NOTIFICATION_URL", "")
    api_key = os.getenv("SEND_NOTIFICATION_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "SEND_NOTIFICATION_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"mobile": mobile, "message": message, "channel": channel},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "send_notification"})
