"""
Tool: send_self_assessment
Description: Sends a self-assessment form to the employee
API: Internal Notification Service
Auto-generated by MAFIA — implement real_send_self_assessment() with your API call.
"""
import os
import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


async def mock_send_self_assessment(emp_id: str, assessment_id: str) -> dict:
    """
    Mock implementation for testing.
    Returns realistic test data — no real API called.
    """
    return {
        "success": True
}


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=4))
async def real_send_self_assessment(emp_id: str, assessment_id: str) -> dict:
    """
    TODO: Implement real Internal Notification Service call here.

    Steps:
    1. Get API URL from environment: os.getenv("SEND_SELF_ASSESSMENT_URL")
    2. Get API key: os.getenv("SEND_SELF_ASSESSMENT_API_KEY")
    3. Make the HTTP call
    4. Return structured response
    """
    url = os.getenv("SEND_SELF_ASSESSMENT_URL", "")
    api_key = os.getenv("SEND_SELF_ASSESSMENT_API_KEY", "")

    if not url:
        raise ValueError("SEND_SELF_ASSESSMENT_URL not set in environment")

    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.post(
            url,
            json={"emp_id": emp_id, "assessment_id": assessment_id},
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        response.raise_for_status()
        return response.json()


async def send_self_assessment(emp_id: str, assessment_id: str) -> dict:
    """
    Sends a self-assessment form to the employee
    Automatically switches between mock and real based on MOCK_MODE env var.
    Set MOCK_MODE=false for production.
    """
    try:
        if MOCK_MODE:
            return await mock_send_self_assessment(emp_id, assessment_id)
        return await real_send_self_assessment(emp_id, assessment_id)
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "tool": "send_self_assessment",
            "mock_mode": MOCK_MODE
        }


# ── Claude Tool Schema ─────────────────────────────────────────
# Auto-registered by CAMS tool registry when placed in src/tools/

TOOL_SCHEMA = {
    "name": "send_self_assessment",
    "description": "Sends a self-assessment form to the employee",
    "input_schema": {
        "type": "object",
        "properties": {
            "emp_id": {"type": "string", "description": "Employee ID to send self-assessment"},
            "assessment_id": {"type": "string", "description": "Assessment ID to track the form"}
        },
        "required": ["emp_id", "assessment_id"]
    }
}
