"""
Tool: send_otp
Description: Send OTP to customer mobile and email
API: SMS Gateway (MSG91/Kaleyra)
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def send_otp(mobile: str, email: str) -> str:
    """Send OTP to customer mobile and email"""
    if MOCK_MODE:
        return '{"sent": true, "reference": "OTP-MOCK-7821", "expires_in": 600}'

    # TODO: Replace with real SMS Gateway (MSG91/Kaleyra) call
    url = os.getenv("SEND_OTP_URL", "")
    api_key = os.getenv("SEND_OTP_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "SEND_OTP_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"mobile": mobile, "email": email},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "send_otp"})
