"""
Tool: upload_document
Description: Upload and store KYC document
API: Internal document store
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def upload_document(document_type: str, document_data: str, application_id: str) -> str:
    """Upload and store KYC document"""
    if MOCK_MODE:
        return '{"uploaded": true, "document_id": "DOC-MOCK-001", "sha256": "abc123"}'

    # TODO: Replace with real Internal document store call
    url = os.getenv("UPLOAD_DOCUMENT_URL", "")
    api_key = os.getenv("UPLOAD_DOCUMENT_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "UPLOAD_DOCUMENT_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"document_type": document_type, "document_data": document_data, "application_id": application_id},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "upload_document"})
