"""
Tool: upload_kra
Description: Upload KYC to KRA registry
API: CAMS/NDML KRA FTP
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def upload_kra(pan_number: str, application_id: str) -> str:
    """Upload KYC to KRA registry"""
    if MOCK_MODE:
        return '{"uploaded": true, "kra_reference": "KRAMOSL001", "provider": "CAMS"}'

    # TODO: Replace with real CAMS/NDML KRA FTP call
    url = os.getenv("UPLOAD_KRA_URL", "")
    api_key = os.getenv("UPLOAD_KRA_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "UPLOAD_KRA_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"pan_number": pan_number, "application_id": application_id},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "upload_kra"})
