"""
Tool: verify_pan
Description: Verify PAN number against NSDL database
API: NSDL PAN Verification API
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def verify_pan(pan_number: str, full_name: str) -> str:
    """Verify PAN number against NSDL database"""
    if MOCK_MODE:
        return '{"valid": true, "name_match": true, "pan_status": "active"}'

    # TODO: Replace with real NSDL PAN Verification API call
    url = os.getenv("VERIFY_PAN_URL", "")
    api_key = os.getenv("VERIFY_PAN_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "VERIFY_PAN_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"pan_number": pan_number, "full_name": full_name},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "verify_pan"})
