"""
Tool: verify_bank
Description: Verify bank account via penny drop
API: Razorpay Penny Drop API
Auto-generated by MAFIA — fill in the real API call in the TODO section below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def verify_bank(ifsc_code: str, account_number: str, account_holder_name: str) -> str:
    """Verify bank account via penny drop"""
    if MOCK_MODE:
        return '{"valid": true, "bank_name": "HDFC Bank", "penny_drop_ref": "PD-MOCK-001"}'

    # TODO: Replace with real Razorpay Penny Drop API call
    url = os.getenv("VERIFY_BANK_URL", "")
    api_key = os.getenv("VERIFY_BANK_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "VERIFY_BANK_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"ifsc_code": ifsc_code, "account_number": account_number, "account_holder_name": account_holder_name},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "verify_bank"})
